### ISSUE TITLE
No Icon component

### ISSUE THREAD

**Issue by delaneyj** [garth/snabbdom-material#1]
Examples use an Icon component but one is not exposed.

It would be great to use [extended set of icons](https://materialdesignicons.com/) cause the [official ones](https://design.google.com/icons/) are missing a ton of really useful ones like brands and is ~1500 icons vs 96.

``` jsx
require('mdi/css/materialdesignicons.css');
const Icon = Component(({children})=> {
    return (
        <i className={`mdi mdi-${children}`}/>
    )
});

//Example
<Icon>github-circle</Icon>
```

Seems to work as desired.

**Comment by garth** [comment]
Icon's are very project specific. Perhaps a set of instructions on how to do it could be included? Even the component could be included and you just need to use icomoon to select your project icons?

**Comment by delaneyj** [comment]
Seems like the materialdesignicons fits the bill of both being material styled and a large set to choose from.  My only real concern is the examples are using components not included and won't work for newcomers.

**Comment by garth** [comment]
ok, I'm in the process of moving the example `<Icon name="menu"/>` into the lib and will include a prepared standard icon set and with instructions on how to customise them.
