### ISSUE TITLE
Buttons using primary not getting updated

### ISSUE THREAD

**Issue by delaneyj** [garth/snabbdom-material#12]
Have a section of code like this

``` jsx
const {page} = state;
<Button flat primary={page ==='about'} onClick={()=>signals.pageChange('about')}><Icon>home</Icon> About</Button>
<Button flat primary={page ==='guide'} onClick={()=>signals.pageChange('guide')}><Icon>map</Icon> Guide</Button>
<Button flat primary={page ==='legal'} onClick={()=>signals.pageChange('legal')}><Icon>gavel</Icon> Legal</Button>
```

And it starts out looking correct, however as I start clicking the buttons and signals get sent the primary color stays and is not reset to initial color.  Is there something missing or does it have to do with snabbdom's diffing?

**Comment by garth** [comment]
Can you let me know it it's still happening with the latest version (1.3), I've just made a big refactor of class handling to work around some issues with the way the snabbdom class plugin works.

**Comment by delaneyj** [comment]
Yes its still happening in 1.3, also you introduced a peer undeclared dependency on _classnames_ module.
