### ISSUE TITLE
Appbar example missing shadow

### ISSUE THREAD

**Issue by delaneyj** [garth/snabbdom-material#2]
[In the docs](http://garth.github.io/snabbdom-material/dist/#/appbar) its states 

> `
> <Appbar fixed> <Appbar.Button style={{ float: 'left' }}>
> ...
> </Appbar>
> `
> See the appbar above.

However the matching code doesn't have a shadow like the AppBar used in the docs nor is there an example of how to configure.

**Comment by delaneyj** [comment]
It appears the paper shadows aren't working as well.

**Comment by garth** [comment]
Do you have normalize.css and the lib/index.css included in your build?

**Comment by delaneyj** [comment]
Sigh, i had normalize but not the index.css.  Does it make sense to have some kind of Container that includes these?  I did it by accident but seems like this will happen often.

**Comment by garth** [comment]
I'd like to embed the css directly in the lib somehow, but not sure how to go about it. If you have and examples of it being done elsewhere then I can try it.

**Comment by delaneyj** [comment]
well if you 'demand' webpack usage a simple 
`
require('normalize.css');
require('snabbdom-material/lib/index.css');
`
in the lib/index.js would do it I think.

**Comment by garth** [comment]
I don't think that will work for a node_module, but I'll look around and see what options are out there.

**Comment by garth** [comment]
Opened #5
