### ISSUE TITLE
npm install didn't download the all modules

### ISSUE THREAD

**Issue by Kalantar81** [garth/snabbdom-material#24]
Grüß gut!
First of all, I wanna thank you for the best tutorial example, that I saw in Snabbdom technology with a webpack binder.
When I make an npm install, its not giving me the all modulies. There are a conflict between some of them. What can you advise to do?

**Comment by garth** [comment]
Morgen,

If you're using npm 3 then you will need to manually install the dependencies which at the moment are:

```
npm install classnames moment snabbdom snabbdom-jsx
```

I hope that helps?

If you are still having conflicts then I would need more details to investigate.

**Comment by Kalantar81** [comment]
Thank you, for information!
Schönen tag.

**Comment by garth** [comment]
I've change the dependencies to be always downloaded now, it will take affect from the next release
