### ISSUE TITLE
it doesn't work with new cerebral-view-snabbdom

### ISSUE THREAD

**Issue by yusufsafak** [garth/snabbdom-material#27]
Hi,
cerebral-view-snabbdom does not export Component.DOM anymore. I tried to change .babelrc (I am new to babel ) but it didn't work. 
Should I rewrite all App components with hyperscript? Or is there any solution to write it with JSX? 
Thanks a lot.

**Comment by garth** [comment]
Sounds like a bug in cerebral-view-snabbdom, maybe log an issue there?

**Comment by garth** [comment]
OK, it seems that jsx is no longer included. you can add support by doing:

```
npm install snabbdom-jsx
npm install transform-react-jsx
```

``` js
// at the top of your component js file(s)
import { html } from 'snabbdom-jsx'
```

then in your .babelrc

``` js
{
  "plugins": [
    [ "transform-react-jsx", { "pragma": "html" } ]
  ]
}
```

**Comment by garth** [comment]
I have also updated the cerebral docs with the above instructions http://www.cerebraljs.com/documentation/cerebral-view-snabbdom
